In [1]:
%env THEANO_FLAGS='device=cpu'

env: THEANO_FLAGS='device=cpu'


In [2]:
import theano
theano.config.device

'cpu'

In [1]:
import theano
theano.config.device

Using gpu device 0: GRID K520


'gpu'

In [2]:
import os

In [3]:
os.chdir('/home/ubuntu/Ext/DeepLearningTutorials/code')

In [4]:
os.getcwd()

'/home/ubuntu/Ext/DeepLearningTutorials/code'

In [5]:
import timeit

In [7]:
# import logistic_sgd as LSGD

In [8]:
start = timeit.default_timer()
# LSGD.sgd_optimization_mnist()
%run logistic_sgd.py
end = timeit.default_timer()
print (end - start)

... loading data
... building the model
... training the model
epoch 1, minibatch 83/83, validation error 12.458333 %
     epoch 1, minibatch 83/83, test error of best model 12.375000 %
epoch 2, minibatch 83/83, validation error 11.010417 %
     epoch 2, minibatch 83/83, test error of best model 10.958333 %
epoch 3, minibatch 83/83, validation error 10.312500 %
     epoch 3, minibatch 83/83, test error of best model 10.312500 %
epoch 4, minibatch 83/83, validation error 9.875000 %
     epoch 4, minibatch 83/83, test error of best model 9.833333 %
epoch 5, minibatch 83/83, validation error 9.562500 %
     epoch 5, minibatch 83/83, test error of best model 9.479167 %
epoch 6, minibatch 83/83, validation error 9.322917 %
     epoch 6, minibatch 83/83, test error of best model 9.291667 %
epoch 7, minibatch 83/83, validation error 9.187500 %
     epoch 7, minibatch 83/83, test error of best model 9.000000 %
epoch 8, minibatch 83/83, validation error 8.989583 %
     epoch 8, minibatch 83/83,

The code for file logistic_sgd.py ran for 22.6s


In [9]:
# import convolutional_mlp as CMLP

In [11]:
start = timeit.default_timer()
# CMLP.evaluate_lenet5()
%run convolutional_mlp.py
end = timeit.default_timer()
print (end - start)

... loading data
... building the model
... training
training @ iter =  0
epoch 1, minibatch 100/100, validation error 9.230000 %
     epoch 1, minibatch 100/100, test error of best model 9.520000 %
training @ iter =  100
epoch 2, minibatch 100/100, validation error 6.180000 %
     epoch 2, minibatch 100/100, test error of best model 6.500000 %
training @ iter =  200
epoch 3, minibatch 100/100, validation error 4.640000 %
     epoch 3, minibatch 100/100, test error of best model 4.850000 %
training @ iter =  300
epoch 4, minibatch 100/100, validation error 3.500000 %
     epoch 4, minibatch 100/100, test error of best model 3.910000 %
training @ iter =  400
epoch 5, minibatch 100/100, validation error 3.020000 %
     epoch 5, minibatch 100/100, test error of best model 3.260000 %
training @ iter =  500


KeyboardInterrupt: 

952.638175964


In [12]:
TPE = 952.638175964/5

In [13]:
print TPE

190.527635193


In [6]:
start = timeit.default_timer()
# LSGD.sgd_optimization_mnist()
%run logistic_sgd.py
end = timeit.default_timer()
print (end - start)

... loading data
... building the model
... training the model
epoch 1, minibatch 83/83, validation error 12.458333 %
     epoch 1, minibatch 83/83, test error of best model 12.375000 %
epoch 2, minibatch 83/83, validation error 11.010417 %
     epoch 2, minibatch 83/83, test error of best model 10.958333 %
epoch 3, minibatch 83/83, validation error 10.312500 %
     epoch 3, minibatch 83/83, test error of best model 10.312500 %
epoch 4, minibatch 83/83, validation error 9.875000 %
     epoch 4, minibatch 83/83, test error of best model 9.833333 %
epoch 5, minibatch 83/83, validation error 9.562500 %
     epoch 5, minibatch 83/83, test error of best model 9.479167 %
epoch 6, minibatch 83/83, validation error 9.322917 %
     epoch 6, minibatch 83/83, test error of best model 9.291667 %
epoch 7, minibatch 83/83, validation error 9.187500 %
     epoch 7, minibatch 83/83, test error of best model 9.000000 %
epoch 8, minibatch 83/83, validation error 8.989583 %
     epoch 8, minibatch 83/83,

The code for file logistic_sgd.py ran for 6.8s


In [8]:
start = timeit.default_timer()
# CMLP.evaluate_lenet5()
%run convolutional_mlp.py
end = timeit.default_timer()
print (end - start)

... loading data
... building the model
... training
training @ iter =  0
epoch 1, minibatch 100/100, validation error 9.230000 %
     epoch 1, minibatch 100/100, test error of best model 9.550000 %
training @ iter =  100
epoch 2, minibatch 100/100, validation error 6.180000 %
     epoch 2, minibatch 100/100, test error of best model 6.480000 %
training @ iter =  200
epoch 3, minibatch 100/100, validation error 4.640000 %
     epoch 3, minibatch 100/100, test error of best model 4.840000 %
training @ iter =  300
epoch 4, minibatch 100/100, validation error 3.500000 %
     epoch 4, minibatch 100/100, test error of best model 3.930000 %
training @ iter =  400
epoch 5, minibatch 100/100, validation error 3.020000 %
     epoch 5, minibatch 100/100, test error of best model 3.270000 %
training @ iter =  500
epoch 6, minibatch 100/100, validation error 2.810000 %
     epoch 6, minibatch 100/100, test error of best model 2.810000 %
training @ iter =  600
epoch 7, minibatch 100/100, validation

The code for file convolutional_mlp.py ran for 8.66m


In [9]:
import numpy as np

In [10]:
import theano.tensor as T

In [11]:
from theano.tensor.shared_randomstreams import RandomStreams

In [12]:
from theano import function

In [13]:
from theano import shared

In [14]:
state_A = shared(np.zeros((10,10)))

In [15]:
state_B = shared(np.zeros((10,1)))

In [16]:
X = T.fmatrix('X')

In [17]:
srng = RandomStreams(seed=7) # seeds all random variables

In [18]:
A = srng.normal((10,10))

In [19]:
B = srng.normal((10,1))

In [20]:
a = function([], A)

In [21]:
b = function([], B)

In [22]:
acc_A = function([], state_A, updates=[(state_A, state_A + a())])

In [23]:
acc_B = function([], state_B, updates=[(state_B, state_B + b())])

In [24]:
print state_A.get_value()

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [25]:
print state_B.get_value()

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [26]:
acc_A()

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [27]:
# print state_A.get_value()

In [28]:
acc_B()

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [29]:
# print state_B.get_value()

In [30]:
z = T.dot((X + state_A.get_value()), state_B.get_value())

In [31]:
print state_A.get_value()

[[  3.04513308e-03  -6.87625766e-01  -1.76176012e+00  -1.03802562e+00
    4.42811698e-01   9.64577962e-03   3.78354788e-01   1.23403215e+00
    5.58887303e-01  -3.67138535e-01]
 [ -6.26724362e-01   4.70386595e-01   2.08239722e+00  -7.98181236e-01
    6.99886799e-01   2.09040952e+00   3.98462951e-01   9.99791771e-02
    1.42433703e+00   1.18448114e+00]
 [ -1.51093352e+00   1.36167872e+00   5.04555941e-01  -3.09021801e-01
   -8.01170230e-01  -1.63582993e+00  -1.14383638e+00  -9.73208964e-01
   -4.19189362e-03  -4.70014691e-01]
 [  6.59505248e-01   5.47440872e-02   4.58689034e-01   5.51887751e-02
    8.71327937e-01  -1.15130007e+00   4.61576700e-01   3.93866181e-01
   -6.22851133e-01  -6.70351670e-04]
 [  5.95144570e-01   1.41512394e+00  -1.56104493e+00   4.07439142e-01
    9.23862755e-01  -1.12355098e-01   2.33901048e+00   1.11907279e+00
   -2.23792839e+00   1.61294389e+00]
 [ -1.04776454e+00   1.41548741e+00   6.38524711e-01  -6.31085396e-01
    4.07980144e-01  -7.00737476e-01  -1.33939

In [32]:
print state_B.get_value()

[[-1.31465781]
 [-1.93436062]
 [-1.14448571]
 [ 0.16946305]
 [-0.80552095]
 [-0.89893657]
 [ 0.6805113 ]
 [-0.54167271]
 [-0.41710612]
 [-1.39900589]]


In [33]:
main = function([X], z)

In [34]:
y = np.float32(np.ones((10,10)))

In [35]:
print y

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [36]:
ans = main(y)

In [37]:
ans_ = np.dot((y + state_A.get_value()), state_B.get_value())

In [38]:
ans == ans_

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]], dtype=bool)

In [39]:
print ans

[[ -4.93507506]
 [-14.68738965]
 [ -6.35927834]
 [ -8.39973388]
 [-10.25060722]
 [-14.12242385]
 [-10.8139351 ]
 [ -5.49433412]
 [ -8.09376912]
 [ -7.88081778]]
